-- MySQL Script generated by MySQL Workbench
-- Sat Feb  8 14:16:25 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema db_my_app
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema db_my_app
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_my_app` DEFAULT CHARACTER SET utf8 ;
USE `db_my_app` ;

-- -----------------------------------------------------
-- Table `db_my_app`.`SUSCRIPTORS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_my_app`.`SUSCRIPTORS` (
  `user_id` INT NOT NULL AUTO_INCREMENT,
  `user_rol` INT NOT NULL,
  `user_lastname` VARCHAR(100) NOT NULL,
  `user_name` VARCHAR(45) NOT NULL,
  `user_birthday` VARCHAR(45) NOT NULL,
  `user_gender` VARCHAR(45) NOT NULL,
  `user_maritalstatus` VARCHAR(45) NOT NULL,
  `user_age` VARCHAR(45) NOT NULL,
  `user_address` VARCHAR(45) NOT NULL,
  `user_localphone` VARCHAR(45) NOT NULL,
  `user_email` VARCHAR(45) NOT NULL,
  `user_profession` VARCHAR(45) NOT NULL,
  `user_pass` VARCHAR(200) NOT NULL,
  `user_status` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`user_id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
